apiVersion: v2
name: todo-app
description: A Helm chart for Todo Chat Bot application with Dapr support
type: application
version: 1.0.0
appVersion: "3.0"

keywords:
  - todo
  - chat
  - dapr
  - microservices

maintainers:
  - name: Todo Team
    email: team@todo-app.com

dependencies: []
