{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}
  labels:
    app: {{ .Values.kafka.name }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      containers:
      - name: {{ .Values.kafka.name }}
        image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
        imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
        ports:
        - name: kafka
          containerPort: {{ .Values.kafka.service.port }}
          protocol: TCP
        - name: controller
          containerPort: 9093
          protocol: TCP
        env:
        {{- range .Values.kafka.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.kafka.persistence.enabled }}
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
        {{- end }}
        {{- if .Values.kafka.resources }}
        resources:
          {{- toYaml .Values.kafka.resources | nindent 10 }}
        {{- end }}
      {{- if .Values.kafka.persistence.enabled }}
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-pvc
      {{- end }}
{{- end }}
